### ISSUE TITLE
Game doesn't start?

### ISSUE THREAD

**Issue by grovdata** [dune-demogroup/roc-hell#1]
Tried running the game from the zip file, extracted the zip and made an .ST image with the contents of it. But the game only reaches the title screen and then nothing happens.

Tested on 520+ 1MB with TOS 1.0 and 1.04, but also in Hatari with STe TOS 2.06. Same issue in Hatari.

**Comment by dune-demogroup** [comment]
We need a message at the first image. Like press "P"...

**Comment by dune-demogroup** [comment]
@grovdata : is it working now? (also, I pushed a "PRESS P..." message on title screen)

**Comment by grovdata** [comment]
Yep, it worked when I press P. Thanks, nice game!
